Repository Vizzuality/ncs-go, pull requests merged in 2022-10, with the labels that each got.

#2 feat: video component[NCS-4]
  package.json
  src/components/video/component.stories.tsx
  src/components/video/component.tsx
  src/components/video/index.ts
  src/components/video/types.d.ts
  src/styles/globals.css
  src/svgs/play.svg
  yarn.lock
Labels: ready to review, feature

#6 feat: overview
  src/components/button/constants.ts
  src/components/confirmation-prompt/component.tsx
  src/components/modal/component.stories.tsx
  src/components/modal/component.tsx
  src/components/modal/content/component.tsx
  src/components/modal/content/constants.ts
  src/components/modal/content/types.ts
  src/components/modal/types.d.ts
  src/containers/home/cards/card/component.tsx
  src/containers/home/cards/card/index.ts
  src/containers/home/cards/card/types.d.ts
  src/containers/home/cards/component.tsx
  src/containers/home/common/contact-form/component.tsx
  src/containers/home/common/hero/component.tsx
  src/containers/home/common/navigation/component.tsx
  src/containers/home/common/navigation/constants.ts
  src/containers/home/common/navigation/types.d.ts
  src/containers/home/overview/component.tsx
  src/containers/home/overview/features/component.tsx
  src/containers/home/pathways/component.tsx
  src/containers/home/stories/component.tsx
Labels: enhancement, ready to review

#10 feat: overview v2 responsive [NCS-09]
  package.json
  src/components/button/constants.ts
  src/components/video/component.tsx
  src/containers/home/about/component.tsx
  src/containers/home/about/features/card/component.tsx
  src/containers/home/about/features/card/index.ts
  src/containers/home/about/features/card/types.d.ts
  src/containers/home/about/features/component.tsx
  src/containers/home/about/features/constants.ts
  src/containers/home/about/features/index.ts
  src/containers/home/about/index.ts
  src/containers/home/about/video/component.tsx
  src/containers/home/about/video/index.ts
  src/containers/home/common/hero/component.tsx
  src/containers/home/contact/component.tsx
  src/containers/home/contact/index.ts
  src/containers/home/overview/component.tsx
  src/containers/home/overview/features/card/component.tsx
  src/containers/home/overview/features/component.tsx
  src/containers/home/overview/features/constants.ts
  src/containers/wrapper/component.tsx
  src/pages/index.tsx
  src/svgs/feature-1.svg
  src/svgs/feature-2.svg
  src/svgs/feature-3.svg
  src/svgs/feature-4.svg
  src/svgs/feature-5.svg
  src/svgs/feature-6.svg
  src/svgs/feature-7.svg
  src/svgs/feature-8.svg
  src/svgs/lock.svg
  tailwind.config.js
  yarn.lock
Labels: ready to review

#18 feat: animate home [NCS-13]
  public/images/home/about/background.svg
  public/images/home/stories/ghana.png
  src/components/button/component.tsx
  src/components/button/constants.ts
  src/components/modal/component.tsx
  src/components/modal/content/component.tsx
  src/components/modal/content/constants.ts
  src/components/modal/content/types.ts
  src/components/modal/types.d.ts
  src/components/toast/component.stories.tsx
  src/components/toast/component.tsx
  src/components/toast/constants.ts
  src/components/toast/index.ts
  src/components/toast/types.d.ts
  src/components/video/component.tsx
  src/components/video/play-control/component.tsx
  src/components/video/play-control/index.ts
  src/constants/motion.ts
  src/containers/home/about/component.tsx
  src/containers/home/about/features/card/component.tsx
  src/containers/home/about/features/card/types.d.ts
  src/containers/home/about/features/component.tsx
  src/containers/home/about/video/component.tsx
  src/containers/home/animated-scroll/component.tsx
  src/containers/home/animated-scroll/index.ts
  src/containers/home/animated-scroll/types.d.ts
  src/containers/home/common/hero/component.tsx
  src/containers/home/common/link-arrow/component.tsx
  src/containers/home/common/link-arrow/index.ts
  src/containers/home/common/link-arrow/types.d.ts
  src/containers/home/contact/component.tsx
  src/containers/home/featured-science/component.tsx
  src/containers/home/featured-science/index.ts
  src/containers/home/footer/component.tsx
  src/containers/home/header/component.tsx
  src/containers/home/header/full-screen-modal/component.tsx
  src/containers/home/header/full-screen-modal/content/component.tsx
  src/containers/home/header/full-screen-modal/content/types.ts
  src/containers/home/header/full-screen-modal/types.d.ts
  src/containers/home/header/mobile-menu-modal/component.tsx
  src/containers/home/header/mobile-menu-modal/menu-button/component.tsx
  src/containers/home/header/subscribe-modal/component.tsx
  src/containers/home/stories/component.tsx
  src/containers/home/stories/list/component.tsx
  src/containers/home/stories/list/story-card/component.tsx
  src/containers/home/stories/samples/component.tsx
  src/containers/home/stories/samples/sample-composition/component.tsx
  src/containers/home/stories/samples/sample-composition/sample-card/component.tsx
  src/containers/home/stories/samples/sample-composition/sample-media/component.tsx
  src/containers/home/stories/samples/sample-composition/sample-media/index.ts
  src/containers/home/stories/samples/sample-composition/sample-media/types.d.ts
  src/lib/utils.ts
  src/pages/_app.tsx
  src/pages/index.tsx
  src/svgs/checkmark.svg
  src/svgs/error.svg
  tailwind.config.js
Labels: ready to review

#19 feat: fixes[NCS-14]
  public/images/home/stories/test.webp
  src/components/button/component.stories.tsx
  src/components/button/constants.ts
  src/components/button/types.d.ts
  src/components/modal/component.tsx
  src/components/toast/component.tsx
  src/components/toast/constants.ts
  src/components/toast/types.d.ts
  src/components/video/play-control/component.tsx
  src/containers/home/about/component.tsx
  src/containers/home/about/video/component.tsx
  src/containers/home/contact/component.tsx
  src/containers/home/featured-science/component.tsx
  src/containers/home/footer/component.tsx
  src/containers/home/header/component.tsx
  src/containers/home/header/full-screen-modal/component.tsx
  src/containers/home/header/full-screen-modal/types.d.ts
  src/containers/home/header/mobile-menu-modal/component.tsx
  src/containers/home/header/subscribe-modal/component.tsx
  src/containers/home/intro/component.tsx
  src/containers/home/stories/component.tsx
  src/containers/home/stories/list/component.tsx
  src/containers/home/stories/samples/component.tsx
  src/containers/home/stories/samples/sample-composition/component.tsx
  src/containers/home/stories/samples/sample-composition/sample-card/component.tsx
  src/containers/home/stories/samples/sample-composition/sample-media/component.tsx
  src/containers/media/component.tsx
  src/containers/media/index.ts
  src/containers/media/types.d.ts
  src/containers/toast-container/component.tsx
  src/containers/toast-container/index.ts
  src/hooks/toast/constants.ts
  src/hooks/toast/index.tsx
  src/hooks/toast/types.d.ts
  src/lib/utils.ts
  src/pages/_app.tsx
  src/pages/_document.tsx
  src/pages/index.tsx
  src/store/home/index.ts
Labels: ready to review

#25 feat: update features[NCS-19]
  src/components/modal/content/component.tsx
  src/containers/home/about/features/card/component.tsx
  src/containers/home/about/features/card/types.d.ts
  src/containers/home/about/features/component.tsx
  src/containers/home/about/features/constants.ts
  src/svgs/arrow-rotated.svg
  src/svgs/arrow-top-right.svg
  src/svgs/feature-1.svg
  src/svgs/feature-2.svg
  src/svgs/feature-3.svg
  src/svgs/feature-4.svg
  src/svgs/feature-5.svg
  src/svgs/feature-6.svg
  src/svgs/feature-7.svg
  src/svgs/feature-8.svg
  src/svgs/features/additional-benefits.svg
  src/svgs/features/carbon-markets.svg
  src/svgs/features/case-studies.svg
  src/svgs/features/climate-mitigation.svg
  src/svgs/features/economic-feasibility.svg
  src/svgs/features/human-perspectives.svg
  src/svgs/features/policies.svg
  src/svgs/features/prototyping-network.svg
Labels: ready to review

#27 Logo
  public/images/home/about/background.svg
  public/images/logo-horizontal.svg
  src/containers/home/about/component.tsx
  src/containers/home/featured-science/pathways/component.tsx
  src/containers/home/featured-science/pathways/desktop/path/component.tsx
  src/containers/home/header/component.tsx
  src/containers/home/header/mobile-menu-modal/component.tsx
  src/containers/home/intro/component.tsx
  src/containers/home/intro/navigation/component.tsx
  src/containers/home/intro/particles/component.tsx
  src/containers/home/intro/particles/logo/circles/circle/component.tsx
  src/containers/home/intro/particles/logo/component.tsx
  src/containers/home/intro/skip/component.tsx
  src/store/home/index.ts
Labels: enhancement, ready to review

#28 fix: minor fixes[NCS-49][NCS-51][NCS-52][NCS-53]
  src/containers/home/about/features/component.tsx
  src/containers/home/contact/component.tsx
  src/containers/home/featured-science/component.tsx
  src/containers/home/footer/component.tsx
  src/containers/home/header/component.tsx
  src/containers/home/stories/list/component.tsx
  src/containers/home/stories/samples/component.tsx
Labels: ready to review

#26 feat: favicon, meta icons, meta tags and contact links[NCS-28][NCS-42][NCS-43][NCS-44][NCS-54][NCS-51]
  public/favicon.ico
  public/images/meta-icons/android-icon-144x144.png
  public/images/meta-icons/android-icon-192x192.png
  public/images/meta-icons/android-icon-36x36.png
  public/images/meta-icons/android-icon-48x48.png
  public/images/meta-icons/android-icon-72x72.png
  public/images/meta-icons/android-icon-96x96.png
  public/images/meta-icons/apple-icon-114x114.png
  public/images/meta-icons/apple-icon-120x120.png
  public/images/meta-icons/apple-icon-144x144.png
  public/images/meta-icons/apple-icon-152x152.png
  public/images/meta-icons/apple-icon-180x180.png
  public/images/meta-icons/apple-icon-57x57.png
  public/images/meta-icons/apple-icon-60x60.png
  public/images/meta-icons/apple-icon-72x72.png
  public/images/meta-icons/apple-icon-76x76.png
  public/images/meta-icons/apple-icon.png
  public/images/meta-icons/browserconfig.xml
  public/images/meta-icons/favicon-16x16.png
  public/images/meta-icons/favicon-32x32.png
  public/images/meta-icons/favicon-96x96.png
  public/images/meta-icons/manifest.json
  public/images/meta-icons/ms-icon-144x144.png
  public/images/meta-icons/ms-icon-150x150.png
  public/images/meta-icons/ms-icon-310x310.png
  public/images/meta-icons/ms-icon-70x70.png
  public/images/social-media/share-image.png
  public/images/social-media/share-twitter.png
  src/containers/home/footer/component.tsx
  src/containers/meta-icons/component.tsx
  src/containers/meta-icons/index.ts
  src/containers/meta-tags/component.tsx
  src/containers/meta-tags/index.ts
  src/containers/meta-tags/types.d.ts
  src/pages/index.tsx
Labels: ready to review
